### PR TITLE
Find duplicate requests

### PR DESCRIPTION
**Pull request by gowthamraj198**
- **Added a new method** to get `a list of urls of the requests that are sent more than once`
- **Returning the list of urls** that are repeated more than once in the HAR file
- **Added a new HAR file** 'http://humanssuck.net/jquery-1.7.1.min.js' request twice
- **Added a test** to verify the length of the list returned by the new method on the above HAR file is 1
- This is very useful **whenever an external plugin** (ex. in the case of lazy loading) t**hat sends the requests more than once**.

### CODE REVIEW

**Comment by mrname** [comment]
Thanks for this feature @gowthamraj198 , very cool idea! Could you please add an example in the README so that users know this feature is available?

**Comment by gowthamraj198** [comment]
Hi - I have covered tests for the new method. Not sure how is it reduced by 0.3%. Can anyone help what would have gone wrong?

Thanks.

**Comment by mrname** [comment]
@gowthamraj198 don't worry about the coverage, this seems to be a case of coveralls being confused. I can confirm that your test definitely covers all the new code you provided.

**Comment by gowthamraj198** [comment]
@mrname Thanks for approving PR. I have the updated README file

**Comment by mrname** [comment]
Thanks @gowthamraj198! If you could please address the suggestion of returning a `dict` instead of `list` as well.

**Comment by gowthamraj198** [comment]
@mrname changed list to dict as per the suggestion.

**Comment by mrname** [comment]
Thanks again for this PR @gowthamraj198 . I might do a slight bit of refactoring but will try to get this released by EOD today.

**Comment by gowthamraj198** [comment]
Thanks @mrname for merging! Yes please feel free to make any changes! I will delete the fork

**Comment by mrname** [comment]
@gowthamraj198 this is launched as version 1.7.0. Thanks again for contributing!

**Pull request merged**
